# Numpy Tutorial
### From freeCodeCamp
https://www.youtube.com/watch?v=QUT1VHiLmmI&t=724s

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.19.2


In [11]:
a = np.array([1,2,3], dtype='int16')
a

array([1, 2, 3], dtype=int16)

In [4]:
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
# get dimension
a.ndim

1

In [7]:
b.ndim

2

Get shape

In [8]:
a.shape

(3,)

In [9]:
b.shape

(2, 3)

Data type

In [12]:
a.dtype

dtype('int16')

In [14]:
# get the size - item size in kb
a.itemsize

2

In [17]:
# Total size
a.size * a.itemsize

6

In [18]:
a.nbytes

6

In [21]:
print(b.dtype)
print(b.itemsize)
print(b.size)
print(b.nbytes)

float64
8
6
48
