# Numpy Tutorial
### From freeCodeCamp
https://www.youtube.com/watch?v=QUT1VHiLmmI&t=724s

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.19.2


In [11]:
a = np.array([1,2,3], dtype='int16')
a

array([1, 2, 3], dtype=int16)

In [4]:
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
# get dimension
a.ndim

1

In [7]:
b.ndim

2

Get shape

In [8]:
a.shape

(3,)

In [9]:
b.shape

(2, 3)

Data type

In [12]:
a.dtype

dtype('int16')

In [14]:
# get the size - item size in kb
a.itemsize

2

In [17]:
# Total size
a.size * a.itemsize

6

In [18]:
a.nbytes

6

In [21]:
print(b.dtype)
print(b.itemsize)
print(b.size)
print(b.nbytes)

float64
8
6
48


### Acessing and changing specific items

In [22]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

In [23]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

Get a specific item
`[row, col]`

In [26]:
a[1, 5]

13

In [27]:
a[1, -2]

13

In [28]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [29]:
a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [30]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [31]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [32]:
# Change an item
a [1, 5]

13

In [33]:
a [1, 5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

### Initialize all sorts of different arrays

In [34]:
# All 0
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [44]:
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [45]:
# Another number (full_like)

a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [47]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [50]:
# Random decimal numbers
np.random.rand(4, 2, 3)

array([[[0.97518932, 0.7732776 , 0.46676001],
        [0.76122269, 0.30082855, 0.37246199]],

       [[0.44020592, 0.89104368, 0.9228986 ],
        [0.42453056, 0.69269964, 0.99666569]],

       [[0.20200784, 0.59668009, 0.95397146],
        [0.2104533 , 0.52604807, 0.83814544]],

       [[0.38837732, 0.90733223, 0.88244109],
        [0.18676591, 0.17239745, 0.2229434 ]]])

In [51]:
np.random.random_sample(a.shape)

array([[0.88693252, 0.14973114, 0.21367443, 0.83114165, 0.43600812,
        0.4911812 , 0.1086946 ],
       [0.85282402, 0.61283786, 0.12164391, 0.62759423, 0.66173877,
        0.69199636, 0.58071994]])

In [59]:
# Random integers
np.random.randint(7, high=21, size=(4, 2))

array([[13, 12],
       [11, 15],
       [10, 16],
       [17, 11]])

In [60]:
# identity
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
# repeat an array a few times
print(a[0])
np.repeat(a, 3, axis=0)

[1 2 3 4 5 6 7]


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 1,  2,  3,  4,  5,  6,  7],
       [ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14],
       [ 8,  9, 10, 11, 12, 20, 14],
       [ 8,  9, 10, 11, 12, 20, 14]])

Challenge:  
1 1 1 1 1  
1 0 0 0 1  
1 0 9 0 1  
1 0 0 0 1  
1 1 1 1 1  

In [72]:
output = np.ones((5, 5), dtype='int8')
output

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [73]:
z = np.zeros((3, 3), dtype='int8')
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [74]:
z[1, 1] = 9
z

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]], dtype=int8)

In [75]:
output[1:4, 1:4] = z
output

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

#### Be careful when copying arrays

In [76]:
a = np.array([1, 2, 3])

In [77]:
b = a

In [78]:
b[0]

1

In [79]:
b[0] = 100

In [80]:
print(a)

[100   2   3]


__This happens because NumPy uses pointers/views like pandas__

## Maths

In [81]:
# Elementwise arithmetics

In [82]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [83]:
a + 2

array([3, 4, 5, 6])

In [84]:
a - 2

array([-1,  0,  1,  2])

In [85]:
a += 2

In [86]:
a

array([3, 4, 5, 6])