# Numpy Tutorial
### From freeCodeCamp
https://www.youtube.com/watch?v=QUT1VHiLmmI&t=724s

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.19.2


In [3]:
a = np.array([1,2,3], dtype='int16')
a

array([1, 2, 3], dtype=int16)

In [4]:
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
# get dimension
a.ndim

1

In [7]:
b.ndim

2

Get shape

In [8]:
a.shape

(3,)

In [9]:
b.shape

(2, 3)

Data type

In [10]:
a.dtype

dtype('int16')

In [11]:
# get the size - item size in kb
a.itemsize

2

In [12]:
# Total size
a.size * a.itemsize

6

In [13]:
a.nbytes

6

In [14]:
print(b.dtype)
print(b.itemsize)
print(b.size)
print(b.nbytes)

float64
8
6
48


### Acessing and changing specific items

In [15]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

In [16]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

Get a specific item
`[row, col]`

In [17]:
a[1, 5]

13

In [18]:
a[1, -2]

13

In [19]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [21]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [22]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [23]:
# Change an item
a [1, 5]

13

In [24]:
a [1, 5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

### Initialize all sorts of different arrays

In [25]:
# All 0
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [27]:
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [28]:
# Another number (full_like)

a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [29]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [30]:
# Random decimal numbers
np.random.rand(4, 2, 3)

array([[[0.78055905, 0.06870547, 0.30011004],
        [0.94765964, 0.58820273, 0.9169712 ]],

       [[0.90379483, 0.70427008, 0.50140408],
        [0.1064503 , 0.72928256, 0.39806589]],

       [[0.39577136, 0.93360696, 0.3139818 ],
        [0.49503166, 0.86891368, 0.59125886]],

       [[0.36350101, 0.84317578, 0.85823049],
        [0.85135015, 0.32276387, 0.09961025]]])

In [31]:
np.random.random_sample(a.shape)

array([[0.74542837, 0.14596224, 0.37092648, 0.6982256 , 0.17549762,
        0.81670328, 0.59615469],
       [0.30180119, 0.20428417, 0.704035  , 0.27421293, 0.17223247,
        0.82508813, 0.56393426]])

In [32]:
# Random integers
np.random.randint(7, high=21, size=(4, 2))

array([[10, 17],
       [15, 11],
       [17, 16],
       [17, 13]])

In [33]:
# identity
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
# repeat an array a few times
print(a[0])
np.repeat(a, 3, axis=0)

[1 2 3 4 5 6 7]


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 1,  2,  3,  4,  5,  6,  7],
       [ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14],
       [ 8,  9, 10, 11, 12, 20, 14],
       [ 8,  9, 10, 11, 12, 20, 14]])

Challenge:  
1 1 1 1 1  
1 0 0 0 1  
1 0 9 0 1  
1 0 0 0 1  
1 1 1 1 1  

In [35]:
output = np.ones((5, 5), dtype='int8')
output

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [36]:
z = np.zeros((3, 3), dtype='int8')
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [37]:
z[1, 1] = 9
z

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]], dtype=int8)

In [38]:
output[1:4, 1:4] = z
output

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

#### Be careful when copying arrays

In [39]:
a = np.array([1, 2, 3])

In [40]:
b = a

In [41]:
b[0]

1

In [42]:
b[0] = 100

In [43]:
print(a)

[100   2   3]


__This happens because NumPy uses pointers/views like pandas__

## Maths

In [44]:
# Elementwise arithmetics

In [45]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [46]:
a + 2

array([3, 4, 5, 6])

In [47]:
a - 2

array([-1,  0,  1,  2])

In [48]:
a += 2

In [49]:
a

array([3, 4, 5, 6])

In [50]:
b = np.array([1, 0, 1, 1])

In [51]:
a +b

array([4, 4, 6, 7])

In [52]:
a ** 2 

array([ 9, 16, 25, 36])

In [53]:
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [54]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

### Linear Algebra

In [55]:
a = np.ones((2,3))

In [56]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [57]:
b = np.full((3,2), 2)

In [58]:
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [59]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

Find determinant

In [60]:
c = np.identity(3)

In [61]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
np.linalg.det(c)

1.0

### Statistics

In [63]:
a = np.array([[1,2,3],[4,5,6]])

In [64]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
np.min(a)

1

In [66]:
np.max(a)

6

In [67]:
# By row
np.min(a, axis=1)

array([1, 4])

In [68]:
np.max(a, axis=0)

array([4, 5, 6])

In [69]:
# Sum up all elements
np.sum(a)

21

### Reorganising Arrays

In [70]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [71]:
before.shape

(2, 4)

In [72]:
# Eg. we want it as an 8x1
after = before.reshape((8,1))

In [73]:
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [74]:
before.reshape((2,2,2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [75]:
# Vertically stacking

In [76]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

In [77]:
np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [78]:
# Horizontal Stack

In [79]:
h1 = np.ones((2,4))

In [80]:
h2 = np.zeros((2,2))

In [81]:
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [82]:
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellanious

__Load Data from file__

In [84]:
np.genfromtxt('data.csv', delimiter=',')

array([[ 1.,  2.,  3., 12.],
       [ 6.,  8.,  7.,  9.],
       [ 5.,  5.,  5.,  5.],
       [ 3.,  6.,  9.,  8.],
       [ 9.,  8.,  7.,  1.]])

In [87]:
file_data = np.genfromtxt('data.csv', delimiter=',')
file_data = file_data.astype('int32')
file_data

array([[ 1,  2,  3, 12],
       [ 6,  8,  7,  9],
       [ 5,  5,  5,  5],
       [ 3,  6,  9,  8],
       [ 9,  8,  7,  1]], dtype=int32)

In [ ]:
__A